version: "1.0"
services:
  kaggle:
    build:
     context: .
     shm_size: '32gb'
    shm_size: '32gb'
    container_name: mammo
    volumes:
     - ../../:/home/working
    working_dir: /home/working
    ports:
     - 8888:8888
    command: jupyter lab --ip=0.0.0.0 --port 8888 --allow-root --NotebookApp.notebook_dir='/tmp/working' --no-browser --NotebookApp.token='mammo'
